version: '3'

services:
  db:
    container_name: "lumbarcheck_test_db"
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=test
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
